import type { BrandTheme } from "../tokens";

export const danadubeTheme: BrandTheme = {
  metadata: {
    key: "danadube",
    name: "Dana Dube & Associates",
    tagline: "Professional support with modern precision",
  },
  colors: {
    primary: "#0F172A",
    primaryForeground: "#FFFFFF",
    primaryHover: "#111827",
    primaryActive: "#020617",
    secondary: "#C9A227",
    secondaryHover: "#B68F1E",
    accent: "#8B5E3C",
    background: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceAlt: "#F8FAFC",
    border: "#E5E7EB",
    text: "#111827",
    textMuted: "#6B7280",
    success: "#166534",
    warning: "#B45309",
    danger: "#B91C1C",
    dangerForeground: "#FFFFFF",
  },
  // TODO: Load Cormorant Garamond + Poppins via next/font/google
  fonts: {
    heading: "Cormorant Garamond, Georgia, serif",
    body: "Poppins, system-ui, sans-serif",
    mono: "JetBrains Mono, ui-monospace, monospace",
  },
  radius: {
    sm: "8px",
    md: "8px",
    lg: "16px",
    xl: "24px",
    pill: "9999px",
  },
  shadow: {
    sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  },
  spacing: {
    xs: "8px",
    sm: "16px",
    md: "24px",
    lg: "32px",
    xl: "40px",
    "2xl": "48px",
    "3xl": "64px",
    "4xl": "80px",
    "5xl": "96px",
  },
  typography: {
    h1: { fontSize: "48px", lineHeight: "56px", fontWeight: 700 },
    h2: { fontSize: "36px", lineHeight: "44px", fontWeight: 600 },
    h3: { fontSize: "32px", lineHeight: "40px", fontWeight: 600 },
    h4: { fontSize: "24px", lineHeight: "32px", fontWeight: 600 },
    body: { fontSize: "16px", lineHeight: "24px", fontWeight: 400 },
    small: { fontSize: "16px", lineHeight: "24px", fontWeight: 400 },
    caption: { fontSize: "16px", lineHeight: "24px", fontWeight: 400 },
  },
};
