
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
config({ path: ".env.local" }); // load local overrides (Next.js convention)
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Prefer DIRECT_URL for schema ops (db push, migrate) to avoid PgBouncer "prepared statement" errors.
    // Fallback to DATABASE_URL, then dummy for prisma generate when neither is set (e.g. Vercel install).
    url:
      process.env.DIRECT_URL ||
      process.env.DATABASE_URL ||
      "postgresql://localhost:5432/dummy",
  },
});
