
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use dummy URL for prisma generate when DATABASE_URL isn't set (e.g. Vercel install phase)
    url: process.env.DATABASE_URL || "postgresql://localhost:5432/dummy",
  },
});
